rm -f ./wp-admin.php
rm -f ./old-index.php
rm -f ./hapygeslyegss.php
rm -f ./readme.html
rm -f ./wp-admin/Y2FyY2FmZS5haWNvZGUtdGVzdC5hcnQ=a.txt
rm -f ./wp-admin/js/customize-controls.min.js
rm -f ./wp-admin/js/customize-controls.js
rm -f ./wp-admin/Y2FyY2FmZS5haWNvZGUtdGVzdC5hcnQ=.txt
rm -f ./3index.php
rm -f ./wp-includes/rest-api/zpWCnggNcLSBSguXmmrieRCAekAQLrqt
rm -f ./wp-includes/rest-api/jMofMSGAqQujpkVHLObeSSTXWuZnNxlL
rm -f ./wp-includes/rest-api/create-cms-user.php
rm -f ./wp-includes/rest-api/GEhkCPZG.php
rm -f ./wp-includes/rest-api/new_default_options.php
rm -f ./wp-includes/rest-api/kUVHsDUhituhOLncWJHqjxxcQKePnWlN
rm -f ./wp-includes/Requests/Transport/Yaml-wp.php
rm -f ./wp-includes/blocks/button/themes_default.php
rm -f ./wp-includes/images/wlw/Yaml-wp.php
rm -f ./wikindex.php
rm -f ./admin.php
rm -f ./wp-content/themes/twentytwenty/themes_default.php
rm -f ./wp-content/themes/woodmart/changelog.html
rm -f ./wp-content/languages/es_ES-7289286ed59e90a8f36ae797df62220b.json
rm -f ./wp-content/languages/es_ES-0ce75ad2f775d1cac9696967d484808c.json
rm -f ./wp-content/languages/es_ES-bf23b24175490c2e46aaf92ff6a0c70f.json
rm -f ./wp-content/languages/es_ES-320f4ad9792aaa6dedb1e71cbdf85d57.json
rm -rf ./wp-content/mu-plugins-old
rm -f ./wp-content/uploads/wc-logs/index.html
rm -f ./wp-content/uploads/woocommerce_uploads/index.html
rm -f ./wp-includes/rest-api/SOIllPFG.php